"""test_a1111_read.py — the viewer reads the A1111 `parameters` chunk it has always written.

Run: python test_a1111_read.py

THE GAP THIS CLOSES. `comfy_meta.extract()` read exactly three things from a PNG: `vv_set_id`,
`vv_set_stage`, and ComfyUI's `prompt` graph. It never looked at the `parameters` chunk — the one
the VV saver builds from values the user WIRED, and the one every Civitai upload depends on. So an
image whose graph the walker can't follow showed no model and no prompt, while the answer sat in
the same file unread.

That is not a hypothetical: it is what a local MinMax H3 video workflow does. The walker looks for
a recognised sampler and a `CLIPTextEncode`; a video graph has neither, so it finds nothing.

The claims:

  * A PNG with a `parameters` chunk and NO graph still reports its model and prompt. This is the
    whole feature, and it is asserted end-to-end through the real `extract()`.
  * The block ROUND-TRIPS. Whatever `_format_parameters` writes, `parse_a1111` reads back — tested
    by generating the text with the real writer rather than by hand, so the two cannot drift.
  * It FILLS GAPS AND NEVER OVERWRITES. Where the graph produced an answer, it stays. This is what
    makes the change additive: no image that already showed metadata can change.
  * It refuses what it doesn't recognise, so a foreign or hand-written `parameters` chunk degrades
    to "no metadata" rather than to WRONG metadata.
  * Two parsing traps that would each fail silently: a settings line is only the LAST line and only
    when it looks like one (a prompt ending "lighting: dramatic" must survive), and `Lora hashes`
    holds commas and colons inside its quotes (a naive split shreds the LoRA names).
"""
import io
import os
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import comfy_meta                                            # noqa: E402
from PIL import Image                                        # noqa: E402
from PIL.PngImagePlugin import PngInfo                       # noqa: E402

failures = []


def check(name, cond, detail=''):
    if cond:
        print('  ok    %s' % name)
    else:
        print('  FAIL  %s%s' % (name, ('\n          ' + str(detail)) if detail else ''))
        failures.append(name)


def png_with(tmp, name, **chunks):
    path = os.path.join(tmp, name)
    info = PngInfo()
    for k, v in chunks.items():
        info.add_text(k, v)
    Image.new('RGB', (8, 8), (30, 60, 90)).save(path, pnginfo=info)
    return path


TMP = tempfile.mkdtemp(prefix='vv-a1111-')
try:
    print('\nReading the A1111 block\n')

    # Generated by the REAL writer, so this test cannot drift from the format it parses.
    meta = {'positive': 'a woman in a cemetery, fog',
            'negative': 'blurry, watermark',
            'model_name': 'minimax_h3_fl2va_pruned_int8_convrot',
            'loras': [{'name': 'filmGrain', 'raw': 'filmGrain.safetensors', 'strength': 0.8}]}
    params = {'steps': 20, 'sampler_name': 'euler', 'cfg': 7.0, 'seed': 12345}
    text = comfy_meta._format_parameters(meta, params, 512, 512)
    print('  written block:')
    for line in text.split('\n'):
        print('    | ' + line)

    got = comfy_meta.parse_a1111(text)
    check('round-trip: the positive prompt comes back',
          got.get('positive') == meta['positive'], got.get('positive'))
    check('  the negative comes back', got.get('negative') == meta['negative'], got.get('negative'))
    check('  the model comes back', got.get('model_name') == meta['model_name'], got.get('model_name'))
    check('  the LoRA is lifted out of the prompt, not left in it',
          [l['name'] for l in got.get('loras', [])] == ['filmGrain']
          and '<lora:' not in (got.get('positive') or ''), got.get('loras'))

    print('\nno negative at all (Flux/Krea zero it) — the line is omitted entirely')
    t2 = comfy_meta._format_parameters(
        {'positive': 'just a positive', 'negative': '', 'model_name': 'krea', 'loras': []},
        params, 512, 512)
    g2 = comfy_meta.parse_a1111(t2)
    check('the positive is still read', g2.get('positive') == 'just a positive', g2.get('positive'))
    check('  and no phantom negative is invented', g2.get('negative') is None, g2.get('negative'))

    print('\nthe two parsing traps')
    trap = ('a portrait, lighting: dramatic\n'
            'Negative prompt: ugly\n'
            'Steps: 20, Sampler: Euler, Model: foo, Lora hashes: "a: 1111111111, b: 2222222222"')
    g3 = comfy_meta.parse_a1111(trap)
    check('a prompt line containing a colon is NOT eaten as settings',
          g3.get('positive') == 'a portrait, lighting: dramatic', g3.get('positive'))
    check('  the real settings line is still found', g3.get('model_name') == 'foo', g3.get('model_name'))
    pairs = comfy_meta._split_a1111_settings(
        'Steps: 20, Model: foo, Lora hashes: "a: 1111111111, b: 2222222222"')
    check('  quoted commas in Lora hashes do not shred the line',
          pairs.get('lora hashes') == 'a: 1111111111, b: 2222222222', pairs.get('lora hashes'))
    check('  and the keys around it survive',
          pairs.get('steps') == '20' and pairs.get('model') == 'foo', pairs)

    print('\nit refuses what it does not recognise')
    for junk, why in (('', 'empty'), ('   ', 'whitespace'),
                      ('just some words with no settings line at all', 'no settings row'),
                      ('{"not": "a1111"}', 'json')):
        g = comfy_meta.parse_a1111(junk)
        check(f'  {why}: no model invented', not g.get('model_name'), g)

    print('\nFILLS GAPS, NEVER OVERWRITES — what makes this additive')
    res = {'positive': 'from the graph', 'negative': None, 'model': None,
           'model_name': 'graph_model', 'loras': [], 'method': 'sampler-trace'}
    comfy_meta._fill_from_a1111(res, text)
    check('a graph-traced positive is left alone', res['positive'] == 'from the graph', res['positive'])
    check('  and a graph-traced model is left alone', res['model_name'] == 'graph_model',
          res['model_name'])
    check('  and the method still says where it came from', res['method'] == 'sampler-trace',
          res['method'])
    res2 = {'positive': None, 'negative': None, 'model': None, 'model_name': None,
            'loras': [], 'method': None}
    comfy_meta._fill_from_a1111(res2, text)
    check('an empty result IS filled', res2['positive'] == meta['positive'], res2['positive'])
    check('  and says the block was where it came from', res2['method'] == 'a1111-chunk',
          res2['method'])

    print('\nEND TO END: a PNG with the block and NO graph — the reported case')
    p = png_with(TMP, 'novideo_graph.png', parameters=text)
    r = comfy_meta.extract(p)
    check('the model is reported', r['model_name'] == meta['model_name'], r['model_name'])
    check('  the prompt is reported', r['positive'] == meta['positive'], r['positive'])
    check('  the negative is reported', r['negative'] == meta['negative'], r['negative'])
    check('  the LoRA is reported', [l['name'] for l in r['loras']] == ['filmGrain'], r['loras'])

    print('\na PNG with NEITHER chunk still reports nothing, and does not raise')
    r2 = comfy_meta.extract(png_with(TMP, 'bare.png'))
    check('no metadata invented from an empty PNG',
          not r2['positive'] and not r2['model_name'], r2)

    print('\nSIDECARS — the only way a video can carry anything')
    # A video is never opened during a scan, so a txt2video run (no still to pair with) had no
    # route to a prompt, a model or a set id at any price.
    vid = os.path.join(TMP, 'clip_00001_.mp4')
    io.open(vid, 'wb').write(b'not really a video')
    check('no sidecar reports None, so the old behaviour is untouched',
          comfy_meta.read_sidecar(vid) is None, comfy_meta.read_sidecar(vid))

    io.open(os.path.join(TMP, 'clip_00001_.txt'), 'w', encoding='utf-8').write(
        'a lighthouse in a storm\n'
        'Negative prompt: blurry\n'
        'VV set id: 20260806-141500-abcd\n'
        'VV set stage: Final\n'
        'Steps: 20, Sampler: Euler, Model: minimax_h3\n')
    sc = comfy_meta.read_sidecar(vid)
    check('a sidecar gives the video a prompt', sc['positive'] == 'a lighthouse in a storm',
          sc['positive'])
    check('  and a model', sc['model_name'] == 'minimax_h3', sc['model_name'])
    check('  and a set id — impossible for a video before this',
          sc['set_id'] == '20260806-141500-abcd', sc['set_id'])
    check('  and a stage', sc['set_stage'] == 'Final', sc['set_stage'])
    check('  method says where it came from', sc['method'] == 'sidecar', sc['method'])
    # THE TRAP, hit on the very first hand-written sidecar: A1111's negative runs to the end of the
    # body (multi-line negatives are legal), so a `VV set id:` line after it gets swallowed whole.
    check("  the negative is JUST the negative, not everything after it",
          sc['negative'] == 'blurry', sc['negative'])

    io.open(vid + '.txt', 'w', encoding='utf-8').write('the specific one\nSteps: 1, Model: winner\n')
    sc2 = comfy_meta.read_sidecar(vid)
    check('clip.mp4.txt wins over clip.txt (more specific, cannot collide)',
          sc2['positive'] == 'the specific one' and sc2['model_name'] == 'winner', sc2['positive'])

    big = os.path.join(TMP, 'huge_00001_.mp4')
    io.open(big, 'wb').write(b'x')
    io.open(os.path.join(TMP, 'huge_00001_.txt'), 'w', encoding='utf-8').write(
        'x' * (comfy_meta.SIDECAR_MAX_BYTES + 10))
    check('an oversized sidecar is refused rather than slurped',
          comfy_meta.read_sidecar(big) is None, 'read it anyway')

    io.open(os.path.join(TMP, 'empty_00001_.mp4'), 'wb').write(b'x')
    io.open(os.path.join(TMP, 'empty_00001_.txt'), 'w', encoding='utf-8').write('   \n')
    check('an empty sidecar yields no method, so it reads as no metadata',
          (comfy_meta.read_sidecar(os.path.join(TMP, 'empty_00001_.mp4')) or {}).get('method') is None,
          'claimed metadata')

    print('\nfinding the sidecar without knowing the counter')
    # The reason none of this could be written automatically: the counter is assigned by whoever
    # writes the video, so a sidecar named ahead of it can only ever guess. Both fallbacks exist so
    # it does not have to — the file is named up to something predictable and stops there.
    nc = os.path.join(TMP, 'run_14-20-52_base_00007_.mp4')
    io.open(nc, 'wb').write(b'x')
    io.open(os.path.join(TMP, 'run_14-20-52_base.txt'), 'w', encoding='utf-8').write(
        'counterless\nSteps: 1, Model: m\n')
    check('a sidecar with no counter is found by a video that has one',
          (comfy_meta.read_sidecar(nc) or {}).get('positive') == 'counterless',
          comfy_meta.read_sidecar(nc))

    # With a run code the sidecar can stop even earlier — ONE file for the whole generation, found
    # from every video it wrote, none of which agree on stage, role word or counter.
    code = 'gen_14-20-52~vvk3n9x7'
    io.open(os.path.join(TMP, code + '.txt'), 'w', encoding='utf-8').write(
        'one for the whole run\nVV set id: S9\nSteps: 1, Model: m\n')
    for variant in (f'{code}_Final_base_00009_.mp4', f'{code}_Final_interp_00002.mp4',
                    f'{code}_Final_00001-audio.mp4'):
        p = os.path.join(TMP, variant)
        io.open(p, 'wb').write(b'x')
        got = comfy_meta.read_sidecar(p) or {}
        check(f'  {variant} finds it', got.get('positive') == 'one for the whole run', got)
    check('  and it carries the set id, which is what puts the video in the set',
          (comfy_meta.read_sidecar(os.path.join(TMP, f'{code}_Final_base_00009_.mp4')) or {})
          .get('set_id') == 'S9', 'no set id')

    # The fallbacks must not become a wildcard: an unrelated video in the same folder gets nothing.
    other = os.path.join(TMP, 'unrelated_00001_.mp4')
    io.open(other, 'wb').write(b'x')
    check('  an unrelated video in the same folder still finds nothing',
          comfy_meta.read_sidecar(other) is None, comfy_meta.read_sidecar(other))

    # ---- the same A1111 block, in EXIF, because a JPEG has no PNG chunks -----------------------
    # Found 2026-08-13 on a Civitai download: 2,822 bytes of EXIF UserComment that every other tool
    # could read and this one could not. The parser was never the problem — extract() bailed on the
    # failed PNG-chunk read before anything else got a look, so a JPEG reported "no meta" however
    # much metadata it carried.
    print('\nEXIF UserComment (JPEG/WebP, which have no PNG chunks)')
    from PIL import Image as _Image  # noqa: E402

    def jpeg_with(name, comment_bytes):
        p = os.path.join(TMP, name)
        im = _Image.new('RGB', (8, 8))
        ex = im.getexif()
        ex.get_ifd(0x8769)[37510] = comment_bytes
        im.save(p, 'JPEG', exif=ex)
        return p

    # The three encodings writers actually use. Byte order is GUESSED, not trusted: the wrong guess
    # yields text full of NULs that still parses, just into nonsense.
    body = ('a jpeg prompt\nNegative prompt: jpeg negative\n'
            'Steps: 29, Sampler: Euler, CFG scale: 6.0, Seed: 657664173')
    for label, blob in (
            ('UNICODE / UTF-16 big-endian', b'UNICODE\x00' + body.encode('utf-16-be')),
            ('UNICODE / UTF-16 little-endian', b'UNICODE\x00' + body.encode('utf-16-le')),
            ('ASCII', b'ASCII\x00\x00\x00' + body.encode('utf-8'))):
        r = comfy_meta.extract(jpeg_with('t.jpg', blob))
        check(f'{label}: prompt', r['positive'] == 'a jpeg prompt', ascii(r['positive'])[:70])
        check('  negative', r['negative'] == 'jpeg negative', ascii(r['negative'])[:70])
        check('  settings', (r['steps'], r['cfg'], r['seed'], r['sampler_name'])
              == (29, 6.0, 657664173, 'Euler'), (r['steps'], r['cfg'], r['seed'], r['sampler_name']))

    # It must never raise, whatever the file is.
    plain = os.path.join(TMP, 'plain.jpg')
    _Image.new('RGB', (8, 8)).save(plain, 'JPEG')
    check('a JPEG with no EXIF reports nothing rather than raising',
          comfy_meta.extract(plain)['positive'] is None)
    notimg = os.path.join(TMP, 'notreally.jpg')
    io.open(notimg, 'wb').write(b'not a jpeg')
    check('  and neither does a file that is not an image',
          comfy_meta.extract(notimg)['positive'] is None)
    check('  read_exif_a1111 returns None for a missing file',
          comfy_meta.read_exif_a1111(os.path.join(TMP, 'nope.jpg')) is None)

    # THE COST RULE: a PNG must never be opened looking for EXIF. Every scan reads every image, so
    # an extra Pillow open per PNG would be paid across the whole library for nothing.
    check('a PNG is never probed for EXIF',
          comfy_meta.read_exif_a1111(png_with(TMP, 'nope.png', parameters=text)) is None)

    print('\nthe set keys still work alongside it')
    r3 = comfy_meta.extract(png_with(TMP, 'stamped.png', parameters=text,
                                     vv_set_id='20260806-141500-abcd', vv_set_stage='Final'))
    check('vv_set_id survives the restructure', r3['set_id'] == '20260806-141500-abcd', r3['set_id'])
    check('  and so does vv_set_stage', r3['set_stage'] == 'Final', r3['set_stage'])
    check('  with the block still read', r3['model_name'] == meta['model_name'], r3['model_name'])
finally:
    shutil.rmtree(TMP, ignore_errors=True)

print('\n' + ('all checks passed' if not failures
              else '%d FAILED:\n  - %s' % (len(failures), '\n  - '.join(failures))))
sys.exit(1 if failures else 0)
